### ISSUE TITLE
Rename `Left` and `Right` to `A` and `B`

### ISSUE THREAD

**Issue by matklad** [rayon-rs/either#25]
Hi! This is a completely crazy idea and is almost centrally a won't fix, because `either` is `1.0`, but I decided to log it anyway. 

I've recently saw an `enum Either<T, U> { A(T), B(U) }` in [warp](https://github.com/seanmonstar/warp/blob/6ddd6ca44c21a7c91b8ba08defbc7a90046a56de/src/generic.rs#L11-L15) and now I think that Haskell's left/right terminology is a mistake :D Here are the benefits of A/B

* Equal length of variants
* Less typing
* Nice symmetry between `.0`, `.1` for pairs and `::A`, `::B` for co-pairs
* "Either A or B" sounds more natural then "Either left or right". Like, we have A/B testing and such.
* `A` and `B` have less semantic meaning than `Left`, `Right`. 
* Naturally extends to more varians: `enum ABC<T, U, V> { A(T), B(U), C(V) }`.

EDIT: apparently, there's no `ab` crate yet :thinking:

**Comment by phungleson** [comment]
I like the idea + I wanted to fix a few things here and there for this repo but it seems like this repo is not very active recently.

Wonder if you/we should fork/create a new repo and work on the new ideas? wdyt? @matklad and also @bluss?

**Comment by cuviper** [comment]
You can already rename it on import, at least: `use either::Left as A;` etc

**Comment by peterjoel** [comment]
The crate could also export it as an alternative form.

**Comment by cuviper** [comment]
> - Nice symmetry between .0, .1 for pairs and ::A, ::B for co-pairs
> - A and B have less semantic meaning than Left, Right.
> - Naturally extends to more varians: enum ABC<T, U, V> { A(T), B(U), C(V) }.

For these points, the [`either_n` crate](https://crates.io/crates/either_n) is another possibility, with numeric variants: `One`, `Two`, ...

**Comment by bluss** [comment]
It seems like a matter of taste and not pressing to change after 1.0. `Either<L, R>` is consistent because the Left parameter is to the left of the right parameter.

Left and Right have more semantic meaning than A, B, in a good way. Left has the antonym Right and you can identify that there are conventionally just two possible outcomes in this space.

**Comment by bluss** [comment]
@phungleson I don't think this repo should be active. I oppose building an advanced Either framework, this should be a microcrate.
