### ISSUE TITLE
Trait to add `right_or(Left)` to `Option<Right>`.

### ISSUE THREAD

**Issue by cheako** [rayon-rs/either#61]
To replace `ok_or(Err)`.

**Comment by zachs18** [comment]
Given that there is already `fn right_or(self: Either<L, R>, val: R) -> R;` (etc.) I think it may be confusing to add `fn right_or(self: Option<R>, val: L) -> Either<L, R>;` (etc.). However, these same-named functions are never on the same type, which would reduce confusion. (If `Either::right_or` were not already part of the public API, I might suggest changing that to `unwrap_right_or` if this feature is added, but that is not an option here.) Also, there is somewhat of precedence for this in `std`, with `Result::unwrap_or` vs `Option::ok_or` analogous to these, although those are not named the same.

Given that `opt.right_or(left)` would be equivalent to `opt.map(Either::Right).unwrap_or(Either::Left(left))`, I'm not sure that this feature would be particularly useful.

If this is added, I would also expect corresponding `left_*` and `*_or_else` methods e.g.

```rs

pub trait OptionExt {
    type T;
    fn right_or<L>(self, val: L) -> Either<L, Self::T>;
    fn right_or_else<L, F: FnOnce() -> L>(self, func: F) -> Either<L, Self::T>;
    fn left_or<R>(self, val: R) -> Either<Self::T, R>;
    fn left_or_else<R, F: FnOnce() -> R>(self, func: F) -> Either<Self::T, R>;
}

impl<T> OptionExt for Option<T> {
    type T = T;
    fn right_or<L>(self, val: L) -> Either<L, T> {
        self.map(Right).unwrap_or(Left(val))
    }
    fn right_or_else<L, F: FnOnce() -> L>(self, func: F) -> Either<L, T> {
        self.map(Right).unwrap_or_else(move || Left(func()))
    }
    fn left_or<R>(self, val: R) -> Either<T, R> {
        self.map(Left).unwrap_or(Right(val))
    }
    fn left_or_else<R, F: FnOnce() -> R>(self, func: F) -> Either<T, R> {
        self.map(Left).unwrap_or_else(move || Right(func()))
    }
}
```

**Comment by cuviper** [comment]
You can also write those with `Option::map_or` and `map_or_else`:

impl<T> OptionExt for Option<T> {
    type T = T;
    fn right_or<L>(self, val: L) -> Either<L, T> {
        self.map_or(Left(val), Right)
    }
    fn right_or_else<L, F: FnOnce() -> L>(self, func: F) -> Either<L, T> {
        self.map_or_else(|| Left(func()), Right)
    }
    fn left_or<R>(self, val: R) -> Either<T, R> {
        self.map_or(Right(val), Left)
    }
    fn left_or_else<R, F: FnOnce() -> R>(self, func: F) -> Either<T, R> {
        self.map_or_else(|| Right(func()), Left)
    }
}
```

... and then I think you might as well write that directly instead of having the extensions.
