### ISSUE TITLE
Generalize inner types for better Serde integration

### ISSUE THREAD

**Issue by Starz0r** [rayon-rs/either#89]
Right now, I'm running into an issue where I'd like to deseralize a type like this:
```rs
#[derive(Deserialize)]
struct Foo<'a> {
    #[serde(borrow)]
    bar: Either<Cow<'a, str>, Baz<'a>>,
}

#[derive(Deserialize)]
struct Baz<'a> {
    #[serde(borrow)]
    xyz: Cow<'a, str>,
}
```
On older versions of Rust/Either/Serde, you'll get an error message like so:
```
   |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^ implementation of `Deserialize` is not general enough
   |
   = note: `Foo<'a>` must implement `Deserialize<'0>`, for any lifetime `'0`...
   = note: ...but `Foo<'_>` actually implements `Deserialize<'1>`, for some specific lifetime `'1`
```

Although running the same code on all updated versions of software just gives you a much longer error.
```
error[E0277]: the trait bound `Either<Cow<'a, str>, Baz<'a>>: Deserialize<'_>` is not satisfied
    --> src/lib.rs:10:10
     |
10   |     bar: Either<Cow<'a, str>, Baz<'a>>,
     |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `Deserialize<'_>` is not implemented for `Either<Cow<'a, str>, Baz<'a>>`
     |
     = help: the following other types implement trait `Deserialize<'de>`:
               bool
               char
               isize
               i8
               i16
               i32
               i64
               i128
             and 137 others
note: required by a bound in `next_element`
    --> /playground/.cargo/registry/src/index.crates.io-6f17d22bba15001f/serde-1.0.192/src/de/mod.rs:1726:12
     |
1724 |     fn next_element<T>(&mut self) -> Result<Option<T>, Self::Error>
     |        ------------ required by a bound in this associated function
1725 |     where
1726 |         T: Deserialize<'de>,
     |            ^^^^^^^^^^^^^^^^ required by this bound in `SeqAccess::next_element`

```

This should be possible, given the fact that I can replace `Either<L, R>` with `Result<Ok, Err>` like so, and it'll actually compile, and act properly in software.

```rs
#[derive(Deserialize)]
struct Foo<'a> {
    #[serde(borrow)]
    bar: Result<Cow<'a, str>, Baz<'a>>,
}
```

Not entirely sure what the deal is, but I believe if `Result` can do it, then `Either` should be able to as well? I'm not sure if there are any technical details getting in the way of implementing this, but there shouldn't be much stopping us from just duplicating the `Result` implementation here.

**Comment by cuviper** [comment]
> the trait `Deserialize<'_>` is not implemented for `Either<Cow<'a, str>, Baz<'a>>`

Have you enabled `either`'s `"serde"` feature? Without that, I do see errors like you've reported, but your example works with that feature enabled. Whereas `Result` always has an implementation from `serde` itself.

> Not entirely sure what the deal is, but I believe if `Result` can do it, then `Either` should be able to as well?

I think it should work here, but this deduction won't always hold, because `serde` can use private internal details in its own trait implementations. In fact, I think `serde_derive` even uses private stuff when deriving for enums, which we couldn't replicate if we were manually implementing these traits. (Those things are technically `pub` as far as the language is concerned, but they're `#[doc(hidden)]` and subject to breaking changes in serde's API, so they're off limits.)

**Comment by Starz0r** [comment]
After filling this out, I'm somewhat embarrassed since, now, for whatever reason, this code example works in my environment. It could possibly be because I removed the `#[serde(borrow)]` attribute from struct, but I really have no idea why it just works all of a sudden as, when I was filling this out, it didn't! Truly baffled on how this went wrong.

Sorry for wasting your time.
