### ISSUE TITLE
New crates.io owner?

### ISSUE THREAD

**Issue by smoelius** [rayon-rs/either#93]
Sorry for being paranoid, but @jswrenn appears to be an owner of this crate on crates.io: https://crates.io/crates/either

<img width="187" alt="Screenshot 2024-01-18 at 10 26 20 AM" src="https://github.com/rayon-rs/either/assets/35515885/81936b91-f105-43be-b0b6-d6c4a22eacf0">

What's odd is that I cannot find a commit from him in this repository. Moreover, I don't see `either` among the repositories in his profile: https://github.com/jswrenn?tab=repositories&q=either&type=&language=&sort=

Is it possible he was added as an owner by mistake?

(@jswrenn Sorry for pinging you, and sorry for speaking about you in the third person.)

**Comment by jswrenn** [comment]
No worries! See the discussion here: https://github.com/indexmap-rs/indexmap/issues/291

Context: I'm the maintainer of Itertools, and either is our only required dependency.

**Comment by smoelius** [comment]
That explains it. Thanks!

**Comment by cuviper** [comment]
Sorry for the confusion! It did occur to me that this might look weird, but I think this arrangement makes sense since he maintains `itertools`, where `either` originated, and it is still the biggest dependent on `either` by far.

**Comment by smoelius** [comment]
> Sorry for the confusion!

No worries. Thanks for the reply!
